### ISSUE TITLE
AutoTDD does not respect image font size

### ISSUE THREAD

**Issue by arne-z** [hpi-swa-teaching/AutoTDD#11]
Using the Demo mode (larger font size for high DPI monitors) causes the ATDD widget to break. See image for details.

![image](https://user-images.githubusercontent.com/38384819/39296611-a70df176-4941-11e8-9e9c-40ffe08d1777.png)

![image](https://user-images.githubusercontent.com/38384819/39296528-70af7154-4941-11e8-95bf-8271cadbdd54.png)

**Comment by MaxiBoether** [comment]
closed due to total UI rewrite
