### ISSUE TITLE
(v3) Overview status bar does not survive change of UI theme

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/AutoTDD#19]
**Describe the bug**
After changing the UI theme, the big status bar button in all ATDDOverview windows becomes gray and loses its color.

**To Reproduce**
1. Open an Overview window and run the tests so it gets green
2. Reduce your font size via Extras menu in the Docking Bar
3. Reset your font size via Extras menu in the Docking Bar
4. See error:
  ![image](https://user-images.githubusercontent.com/38782922/82089235-8a50ec80-96f3-11ea-999a-f181171ca6cc.png)

**Expected behavior**
The status button should keep green.

**Comment by benjamin-frost** [comment]
Resolved in #40
