### ISSUE TITLE
MetaProgramming: TarTrafficLight>>testSuite

### ISSUE THREAD

**Issue by philipp94831** [hpi-swa-teaching/AutoTDD#2]
Need to find a better solution for this piece of meta-programming without altering `TestCase class`.
In 4.4 there was a method `TestCase class>>isTestCaseClass`

![MetaProgramming](https://cloud.githubusercontent.com/assets/2177801/2889844/749a5726-d522-11e3-8501-9b2d6a9a2e08.png)

**Comment by MaxiBoether** [comment]
fixed by using InheritsFrom + total rewrite
