### ISSUE TITLE
Use a less eye-hurting green for successful tests

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/AutoTDD#21]
If a test passes, that's a fine thing which I usually am happy about. However, the green tone used by AutoTDD for displaying passed tests is so light and eye-hurting that it can dampen my fun a bit.

Please consider using `Color green muchDarker` instead. Compare yourself:

![image](https://user-images.githubusercontent.com/38782922/82127358-27bf2580-97b3-11ea-8f01-aa4d88fbb646.png)

**Probably related**
Make AutoTDD look great in every UI theme.

**Comment by benjamin-frost** [comment]
Resolved in #43

@LinqLover If you feel like the colors are not appropriate feel free to re-open this issue
