### ISSUE TITLE
Speed Improvement: Run Tests in another image

### ISSUE THREAD

**Issue by kolioOtSofia** [hpi-swa-teaching/AutoTDD#31]
As a <kbd>client</kbd> I want the tests to run in parallel, so in another squeak image, so that I can get better performance

### Acceptance criteria

- [ ] When opening AutoTDD in another Image it should run even when the changes are in another Squeak Image

### Effort Evaluation

Points: 13 (open for expert revision (Patrick))

**Comment by benjamin-frost** [comment]
Considering that this user story is quite heavy it will be split up into multiple smaller user stories!
