### ISSUE TITLE
Add third row for the GitHub Actions Status in the Quick overview

### ISSUE THREAD

**Issue by kolioOtSofia** [hpi-swa-teaching/AutoTDD#55]
As a `user` I want to have the same consistent design in the Quick overview Window for the GitHub Actions, so that the status can be displayed in a consistent way later on. 

### Accenptance Criteria
-[ ] There is a dedicated third row for the GitHub Actions in the Quick Overview

### Effort evaluation 
2 Points

**Comment by Benjamin-Frost** [comment]
Duplicate of #42
