### ISSUE TITLE
Replace Titles with Hover-Text

### ISSUE THREAD

**Issue by benjamin-frost** [HPI-SWA-Teaching/AutoTDD#87]
As a <kbd>*designer*</kbd> I want to *have hover texts instead of headlines* in order to *improve the UI of the browser* (suggestion by Patrick - as this is more common in Squeak than Headlines).

### Acceptance criteria

- [x] Titles removed
- [x] Hover-Texts added

### Effort Evaluation

Points: 2

**Comment by SebastianWagner2** [comment]
```
buildTokenWith: aBuilder
	
	^ aBuilder pluggableInputFieldSpec new
		model: token;
		**help: self class tokenHelpLabel;**
		getText: #contents;
		setText: #contents:;
		softLineWrap: true;
		yourself
```
