### ISSUE TITLE
Broken (MNU) in latest Squeak due to Theming preferences changes

### ISSUE THREAD

**Issue by j4yk** [HPI-SWA-Teaching/AutoTDD#9]
The theming changes to the latest Squeak seem to have broken AutoTDD. Clicking on the wrench icon got me a Debugger for MNU: Preference class>>workspaceWindowColor.

Full stack details here: https://gist.github.com/j4yk/917ac9ebaafe8b4a7fbd71275b2e3385

#### short stack trace:

MessageNotUnderstood: Preferences class>>workspaceWindowColor

Preferences class(Object)>>doesNotUnderstand: #workspaceWindowColor
[] in Preferences class>>doesNotUnderstand: #workspaceWindowColor
[] in Preferences class>>valueOfPreference:ifAbsent:
IdentityDictionary(Dictionary)>>at:ifAbsent:
Preferences class>>preferenceAt:ifAbsent:
Preferences class>>valueOfPreference:ifAbsent:
Preferences class>>doesNotUnderstand: #workspaceWindowColor
ATDDTrafficLight>>drawLineOn:
ATDDTrafficLight>>drawSettingsOn:
ATDDTrafficLight>>drawOn:
AnimFormCanvas(Canvas)>>draw:
AnimFormCanvas(Canvas)>>drawMorph:
ATDDTrafficLight(Morph)>>fullDrawOn:
ATDDTrafficLight(Morph)>>fullDrawAnimatedOn:
AnimFormCanvas>>fullDrawMorph:
[] in [] in AnimWorldState(WorldState)>>drawWorld:submorphs:invalidAreasOn:
Rectangle>>allAreasOutsideList:startingAt:do:
Rectangle>>allAreasOutsideList:do:
[] in AnimWorldState(WorldState)>>drawWorld:submorphs:invalidAreasOn:
Array(SequenceableCollection)>>do:

**Comment by fniephaus** [comment]
Fixed with https://github.com/HPI-SWA-Teaching/AutoTDD/commit/f09ef6a459d458da188e1a74a4db0ed4c1261e77.
